version: 0.1

version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - dist/bundle.js
    - img/*
    - js/*
    - css/*
    - contact/*
